export const adsList = [
    {
        id: 0,
        image: 'https://cf.shopee.vn/file/6c8fc3c9636ecb550fa40dfbcc4a13b1',
        isClose: true,
        url: 'https://shope.ee/5ztGui68zA',
        name: 'Tai Nghe Mèo Bluetooth Chụp Tai STN28, Có Micro, Âm Thanh Siêu Bass. Headphone Con Mèo Chơi Game, Học Online',
    },
    {
        id: 1,
        image: 'https://cf.shopee.vn/file/sg-11134201-22120-i402ii025xkvea',
        isClose: true,
        url: 'https://shope.ee/9emZI8WPq4',
        name: 'Loa thông minh Divoom Ditoo Plus 10W - Hình dáng máy tính cổ, màn hình LED 256 Full RGB',
    },
    {
        id: 2,
        image: 'https://cf.shopee.vn/file/68f314fab5b78aea54c44f04d2e84a3d',
        isClose: true,
        url: 'https://shope.ee/2pwFAQxQor',
        name: '[BH 1 đổi 1] Loa bluetooth Q5 bản cao cấp nhất hiện tại, kiêm đồng hồ, báo thức,nghe nhạc, nghe đài FM, hiển thị đèn led',
    },
    {
        id: 3,
        image: 'https://cf.shopee.vn/file/1b9af62237660a437794e0aaeb4f3d50',
        isClose: true,
        url: 'https://shope.ee/5AK9wyD9Mm',
        name: 'Loa Máy Tính ROBOT RS200 Hiệu Ứng RGB LED Đổi Màu - Âm Thanh HD Sống Động Chất Lượng Cao',
    },
    {
        id: 4,
        image: 'https://cf.shopee.vn/file/a3dfc45a9b4bc69caefd51a73abe5241',
        isClose: true,
        url: 'https://shope.ee/1L7RORastB',
        name: 'Đèn hoàng hôn 16 màu kèm điều khiển chuyển đổi 16 màu khác nhau RGB - Rabbi HCM',
    },
    {
        id: 5,
        image: 'https://cf.shopee.vn/file/85ac338a96d9a1a49044d3ed33f3ab6a',
        isClose: true,
        url: 'https://shope.ee/A9it4XU8Z7',
        name: 'Loa bluetooth mini không dây , loa nhà tắm chống thấm nước nhỏ gọn tiện dụng _ tặng kèm sticker đẹp dễ thương',
    },
    {
        id: 6,
        image: 'https://cf.shopee.vn/file/0194c1ebca9a5c2406653f328a5df851',
        isClose: true,
        url: 'https://shope.ee/6ACkOZtMVr',
        name: 'Tai Nghe Mèo Bluetooth Cao Cấp, Headphone Tai Mèo Đáng Yêu, Có Mic, Chống Ồn - Bảo Hành 12 Tháng',
    },
    {
        id: 7,
        image: 'https://cf.shopee.vn/file/sg-11134201-22120-zubodryd3nlv77',
        isClose: true,
        url: 'https://shope.ee/6ACkOjGT7E',
        name: 'Micro Karaoke Bluetooth WK D23 mic hát karaoke chất lượng tốt - Hỗ trợ ghi âm',
    },
];
